logo:
  favicon: /images/site/favicon.png

topNavbar:
  maxVisibleSections: 5

features:
  theme:
    enable: true
    services:
      light: true
      dark: true
      default: system

  portfolio:
    enable: true

  blog:
    enable: false

  notes:
    enable: false

  comment:
    enable: false

  analytics:
    enable: false

  toc:
    enable: false

  tags:
    enable: false

  flags:
    enable: false

  embedpdf:
    enable: false

  flowchart:
    enable: false

  math:
    enable: false

  syntaxHighlight:
    enable: true
    services:
      hljs:
        noHighlightRe: /^no-highlight$/i

  copyCodeButton:
    enable: true

  readingTime:
    enable: false

footer:
  enable: true
  template: footer.html
  navigation:
    enable: true
  contactMe:
    enable: true
  credentials:
    enable: true
  newsletter:
    enable: false
  disclaimer:
    enable: false
