name: Test renovate.json

on:
  pull_request:
    branches:
      - master
    paths:
      - renovate.json5
      - .github/workflows/dry-run-renovate.yaml

jobs:
  renovate:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install Renovate CLI
        run: npm install renovate

      - name: Dry-run Renovate
        run: |
          npx renovate '${{ github.repository }}' \
            --dry-run=full \
            --use-base-branch-config=merge
        env:
          RENOVATE_USERNAME: renovate[bot]
          RENOVATE_GIT_AUTHOR: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
          RENOVATE_TOKEN: ${{ github.token }}
          # Use renovate.json in the commit `github.sha`.
          RENOVATE_BASE_BRANCHES: ${{ github.sha }}
          RENOVATE_CONFIG_FILE: renovate.json5
          LOG_LEVEL: debug